common: &common
  adapter: postgresql
  username: Rtastic
  password: Rtastic # from psql setup, see Postgresql

development:
  <<: *common
  database: Rtastic_development

test:
  <<: *common
  database: Rtastic_test

production:
  <<: *common
  database: Rtastic_production